github.com:
    users:
        himath-adithya:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: himath-adithya
