[[language]]
name = "latex"
indent = {tab-width = 2, unit = " "}

[[language]]
name = "rust"
indent = {tab-width = 2, unit = " "}

# [[language]]
# name = "nasm"
# indent = {tab-width = 2, unit = " "}
